### ISSUE TITLE
Navbar need add phpdoc @method begin() and Nav need add @method widget()

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii-bootstrap4#19]
### What steps will reproduce the problem?

I Installed yii-demo , and open the project in vscode. views/layout/main.php

### What is the expected result?
intelephense show message 
Undefined method 'brandLabel'
Undefined method 'currentPath'

![image](https://user-images.githubusercontent.com/1013744/80943097-fc365580-8e18-11ea-81ac-f7a8fd6fe2d6.png)

**Comment by samdark** [comment]
Please try updating and check again. Thanks.

**Comment by pigochu** [comment]
@samdark 

Thank you.
