### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii-bootstrap4#25]
Hi devs,

Can you please make a `yii-bootstrap5` copy from this repo? We can build and change from there with the latest [alpha release](https://v5.getbootstrap.com/).

**Comment by samdark** [comment]
Done https://github.com/yiisoft/yii-bootstrap-5.

**Comment by Thoulah** [comment]
Thank you!
Which one is named incorrectly? `yii-bootstrap4` or `yii-bootstrap-5` (meaning the second dash)

**Comment by samdark** [comment]
Second one. Fixed.

**Comment by Thoulah** [comment]
Sorry to bother you agan. Can you please publish the package to packagist?

**Comment by samdark** [comment]
Done.
