### ISSUE TITLE
Problem ActiveField Init Config.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-bootstrap4#5]
### What steps will reproduce the problem?
Layout config ActiveField

### What's expected?
Create config Layout ActiveField

### Additional info
```
ActiveField.php (work)
/**
* {@inheritdoc}
*/
public function init(): void
{
    $layoutConfig = $this->createLayoutConfig();
    $config = ArrayHelper::merge($layoutConfig, ArrayHelper::getObjectVars($this));
    AbstractContainer::configure($this, $config);
}
```
ActiveField.php (no works)
```
/**
* {@inheritdoc}
*/
public function init(): void
{
    AbstractContainer::configure($this, $this->createLayoutConfig());
}

```

**possible solution:**
```
/**
 * Constructor for activefield
 */
public function __construct(array $config = [])
{
  if (!empty($config)) {
       	AbstractContainer::configure($this, $this->createLayoutConfig());
  }
}
```

| Q                | A
| ---------------- | ---
| Yii vesion       | 3.0
| PHP version      | 7.1.23
| Operating system | Centos 7

**Comment by machour** [comment]
@terabytesoftw it seems that your PR broke tests.

Could you show the code you were using when you found the problem? "Layout config ActiveField" isn't clear enough.
