### ISSUE TITLE
yiisoft/yii-bootstrapX maintenance

### ISSUE THREAD

**Issue by machour** [yiisoft/yii-bootstrap4#7]
Opening a discussion about `yii-bootstrap3` & `yii-bootstrap4` maintenance.

Since at this exact moment, both these packages are "perfect" copies (with Yii3 adaptations) of [yii2-bootstrap](https://github.com/yiisoft/yii2-bootstrap) & [yii2-bootstrap4](https://github.com/yiisoft/yii2-bootstrap4), I feel that we may want to adopt the following rules to avoid divergences between the two versions: 

- Only accept new features & enhancements in Yii 2 packages (most activity for now)
- Only update Yii 3 packages to backport new changes in Yii 2 packages, or improve the internal Yii-3 stuff (di, config, etc)

Someone could easily watch over Yii 2 changes an be responsible of copying.

**Comment by samdark** [comment]
Sounds OK to me. Do you want to take care of these?

**Comment by machour** [comment]
Best thing would be to setup some sort of hook for merges/commits in yii2 repos to open issues in the new ones. 

https://github.com/probot might help here.

**Comment by samdark** [comment]
Any specific bot for that?
