### ISSUE TITLE
bower-asset defined, but npm-asset actually used

### ISSUE THREAD

**Issue by onyn** [yiisoft/yii-bootstrap4#8]
This package defines dependency on bower-asset in composer.assets.json:

https://github.com/yiisoft/yii-bootstrap4/blob/ce4efdfb6a9c6c966b9dbc02a1826a67060812ce/composer.assets.json#L3

But refers to npm in the code:

https://github.com/yiisoft/yii-bootstrap4/blob/ce4efdfb6a9c6c966b9dbc02a1826a67060812ce/src/BootstrapAsset.php#L19

https://github.com/yiisoft/yii-bootstrap4/blob/ce4efdfb6a9c6c966b9dbc02a1826a67060812ce/src/BootstrapPluginAsset.php#L19

This leads to failure on asset publishing:

```
Invalid Argument – yii\exceptions\InvalidArgumentException
The file or directory to be published does not exist: /var/www/vendor/npm-asset/bootstrap/dist
```

**Comment by machour** [comment]
Yes, it changed in yii2-bootstrap4 but wasn't ported here yet. (see #7)

We need to synchronize again starting at this commit: https://github.com/yiisoft/yii2-bootstrap4/commit/98d0c63cfa7db447881afb63b099f4d5c0ea95cb

Would you like to open a PR for that?

**Comment by onyn** [comment]
I can simply rebase all those commits on top of this repo's head. Is this would be enough?

**Comment by machour** [comment]
I think so. I'll review & merge.

**Comment by terabytesoftw** [comment]
yii3 work with foxy, and hiqdev and it is installed by default in /node_modules

**Comment by terabytesoftw** [comment]
Done.
